app = "locar-vision"

[build]
  image = "python:3.9-slim"

[env]
  PORT = "5000"

[deploy]
  strategy = "rolling"

[services]
  [[services.http]]
    internal_port = 5000
    force_https = true

    [services.http.concurrency]
      soft_limit = 25
      hard_limit = 50

    [[services.http.ports]]
      port = 80
      handlers = ["http"]
    [[services.http.ports]]
      port = 443
      handlers = ["tls", "http"]
